config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :articles do
    resources:comments
  end
  resources :customers 
   
  resources :orders   

  resources :suppliers
  
  resources :accounts

  resources :assemblies do
    get 'all_parts' 
  end  

  resources :parts do

    collection do
      get 'list'
      post 'create_list'
      get 'show_list'
    end
    get 'all_assembly'
  end

  resources  :registerusers
  
  resources :books do
    collection do
      get 'book_list' 
    end  
  end  
  
  get  'signup'  => 'users#new'
  post 'users' => 'users#create' 

 

  
end

app/models/account.rb
class Account <ActiveRecord::Base
	belongs_to :supplier
	validates :account_number,presence:true,length: { in: 6..20 },uniqueness: true
	
end	

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates:title,presence:true,
					length: { minimum: 5 }
end

app/models/assembly.rb
class Assembly < ActiveRecord::Base
  has_and_belongs_to_many :parts
end

app/models/assembly_part.rb
class AssemblyPart < ActiveRecord::Base
  self.table_name = "assemblies_parts"
  belongs_to :part
  belongs_to :assembly
end  

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :subject
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders
	validate :custom_validation

	def custom_validation
		errors.add(:name, "You must enter name") if name.blank?
		
	end
end

app/models/info.rb
class Info < ActiveRecord::Base
	validates :name, length: { minimum: 4, too_short:"must have at least four words " }
	validates :password,length:{ in: 6..20},  numericality:true
	validates :registration_no ,length:{is:6} :on => :create
end

app/models/manufacture.rb
class Manufacture < ActiveRecord::Base
	has_many :product_infos
end	

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  validate :custom_validation

  def custom_validation
  	errors.add(:order_name,"you must enter order_name") if order_name.blank?
  end
  	
end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
end

app/models/part.rb
class Part < ActiveRecord::Base
  has_and_belongs_to_many :assemblies
  before_save :update_data

  private

  def update_data
    self.part_number = "dummy" + self.part_number
  end
end

app/models/product_info.rb
class ProductInfo < ActiveRecord::Base
  belongs_to :manufacture
end

app/models/register_user.rb
class RegisterUser < ActiveRecord::Base
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :name, :presence =>true, :uniqueness => true, :length => {:in => 3..20 }
  validates :email , :presence => true, :uniqueness => true ,:format => EMAIL_REGEX

  #after_save :send_confirmation

  private

  def send_confirmation
    UserMailer.send_signup_email(self).deliver
  end  
end

app/models/subject.rb
class Subject <ActiveRecord::Base
  has_many :books
end  

app/models/supplier.rb
class Supplier <ActiveRecord::Base
  has_one :account
  validates :name,:presence => {:message => "can't be blank"}
end	

app/models/supplier_info.rb
class SupplierInfo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
	validates :username, :presence =>true, :uniqueness => true, :length => {:in => 3..20 }
	validates :email , :presence => true, :uniqueness => true ,:format => EMAIL_REGEX
	validates :password, :confirmation => true
	validates_length_of :password, :in => 6..20 ,on: :create
	 
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  
  def new 
    @part = Part.new
  end
  
  def create
    @part = Part.new(part_params)
    if @part.save
      redirect_to list_parts_path
    else
      render :new   
    end 
  end

  def list
    @part = Part.all
    @assemblie = Assembly.all
  end

  def create_list
    AssemblyPart.create(assembly_id: params[:assembly_id], part_id: params[:part_id])
    redirect_to  show_list_parts_path
  end

  def show_list
    @all_assembly_parts = AssemblyPart.all
  end   

  def all_assembly
    @assemblies = []
    p part = Part.where(id: params[:part_id]).first
    @assemblies = part.try(:assemblies) if part
  end  
    
  private 
  def part_params
    params.require(:part).permit(:part_number)
  end 

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/parts/all_assembly.html.erb
<%@assemblies.each do |assembly| %>
<span>name:<%=assembly.name %> </span>
<%end%>

app/views/parts/index.html.erb
<div style="text-align: center;">
	<%= @parts.each do |part|  %>
	<% end %>
</div>

app/views/parts/list.html.erb
<div style="text-align: center;">
<%= form_tag (create_list_parts_path) do %>
	<p style="border-bottom: 2px solid"><strong>Supplier and Order</strong></p>
	<%#= collection_select  Part.all, :id, :name%>
	<div style="padding-bottom:20px;">
		<label> Assembly name:-</label>
		<%= select_tag "assembly_id", options_for_select(@assemblie.collect{ |assembly| [assembly.name, assembly.id]}),prompt: "---Select assembly number---" %>
	</div>
	
	<label> part number:-</label>
	<%= select_tag "part_id", options_for_select(@part.collect{ |part| [part.part_number, part.id]}),prompt: "---Select part number---" %></br>

	<div class="btn-submit">
		<%= submit_tag "Save"%>
	</div>

<% end %>
</div>

app/views/parts/new.html.erb
<%= form_for @part do |f| %>

<div class="supplier-form">
	<div style=" width: 12%;margin-left: 44%;">
		<%=f.text_field :part_number ,class:'text-field',placeholder: 'part name' %></br>
	</div>
	<div class="btn-submit">
		<%= f.submit :Save %>
	</div>
</div>
<% end %>

app/views/parts/show_list.html.erb
<table>
	<th> assembly id</th>
	<th> part id</th>
	<% @all_assembly_parts.each do |a_part| %>
	<tr>
		<td >
		<%= a_part.assembly_id %>
		<%= link_to 'show', "/assemblies/#{a_part.assembly_id}/all_parts" %>
		</td>
		<td >
		<%= a_part.part_id %>
		<%= link_to 'show', "/parts/#{a_part.part_id}/all_assembly" %>
		</td>
	</tr>
	<% end %>
</table>